I0
	S' -> .S , $
	S -> .C C , $
	C -> .c C , c
	C -> .c C , d
	C -> .d , c
	C -> .d , d

I1
	S' ->  S., $

I2
	S ->  C.C , $
	C -> .c C , $
	C -> .d , $

I3
	C ->  c.C , c
	C -> .c C , c
	C -> .d , c
	C ->  c.C , d
	C -> .c C , d
	C -> .d , d

I4
	C ->  d., c
	C ->  d., d

I5
	S ->  C C., $

I6
	C ->  c.C , $
	C -> .c C , $
	C -> .d , $

I7
	C ->  d., $

I8
	C ->  c C., c
	C ->  c C., d

I9
	C ->  c C., $

